baseURL = "https://eminakamura.github.io/"
relativeURLs = true
title = "Emi Nakamura"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "E. Morris Cox Professor of Economics, University of California, Berkeley"
    logo = "index_files/image001.jpg"
    faviconVersion = "4"
    
